# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de8de161a52ec60c72f0151bc2779a42487dfa340dbe44860a2376363b28a6a4a7a82b4763ece59f1b28271d8c85972c47b351572c8aded5c81ce142b762240

test:
  secret_key_base: 90c8fd76f94577b4b4c677081a222322b386804f3e58dade6dd8d4535b14256903534ce4bf1d0ec60cafebeeedefd99a00613313be85d0cd4b1961ae96896917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
